# Generated by Django 5.2.5 on 2025-08-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateField(auto_now_add=True)),
                ('new_events_count', models.PositiveIntegerField(default=0)),
                ('updated_events_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
